version: 2.1
jobs:
  build:
    working_directory: ./app
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run tests
          command: |
            npm test
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKER_USERNAME/circleci-new-docker-example:$TAG .
      - run:
          name: Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKER_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/circleci-new-docker-example:$TAG
      