version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
    - run:
        name: Run tests
        command: |
          npm test
  build:
    working_directory: .
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            TAG=${CIRCLE_SHA1}
            docker build -t $DOCKER_USERNAME/circleci-devops-teste:$TAG .
      - run:
          name: Push application Docker image
          command: |
            TAG=${CIRCLE_SHA1}
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/circleci-devops-teste:$TAG
      - run:
          name: Deploy to ecs
          command: |
            TAG=${CIRCLE_SHA1}
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/circleci-devops-teste:$TAG
    deploy-to-ecs:
      jobs:
        - aws-ecs/deploy-service-update: # orb built-in job
          requires:
            - build
          family: '${MY_APP_PREFIX}-service'
          cluster: '${ECS_CLUSTER}'
          container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
      
      