version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@0.0.10
workflow:
  jobs:
    test:
      docker:
        - image: cimg/base:stable
      steps:
      - run:
          name: Run tests
          command: |
            npm test
    build:
      working_directory: .
      docker:
        - image: cimg/base:2022.09
          auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
      steps:
        - checkout
        - run:
            name: Build Docker image
            command: |
              TAG=${CIRCLE_SHA1}
              docker build -t $DOCKER_USERNAME/circleci-devops-teste:$TAG .
        - run:
            name: Push application Docker image
            command: |
              TAG=${CIRCLE_SHA1}
              echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
              docker push $DOCKER_USERNAME/circleci-devops-teste:$TAG
    deploy-to-ecs:
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          aws-region: ${AWS_DEFAULT_REGION}
          family: "${MY_APP_PREFIX}-service"
          cluster-name: "${ECS_CLUSTER}"
          container-image-name-updates: "container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'"
          verify-revision-is-deployed: true

      
        