name: pipeline-actions

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Set up Node
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # Step 3: Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          cd app
          npm install
          npm test

      # Step 4: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 6: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-teste:${{ github.run_id }}

      # Step 7: Deploy to EC2
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.AWS_HOST_EC2 }}
          USER_NAME: ${{ secrets.AWS_HOST_EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
           if docker ps --filter "name=devops-teste" --format "{{.Names}}" ; then
              echo "Container não encontrado, subindo."
              docker run -d --name devops-teste -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/devops-teste:${{ github.run_id }}
            else
              docker stop $(docker ps --filter "name=devops-teste" --format "{{.ID}}")
              docker container rm devops-teste
              docker run -d --name devops-teste -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/devops-teste:${{ github.run_id }}


            fi
            
          '
